// Mocks generated by Mockito 5.4.6 from annotations
// in clientapp/test/app/view/app_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:blog_domain/src/model/blog_post.dart' as _i2;
import 'package:blog_domain/src/repository/blog_post_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBlogPost_0 extends _i1.SmartFake implements _i2.BlogPost {
  _FakeBlogPost_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BlogPostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlogPostRepository extends _i1.Mock
    implements _i3.BlogPostRepository {
  @override
  _i4.Future<List<_i2.BlogPost>> fetchBlogPosts() =>
      (super.noSuchMethod(
            Invocation.method(#fetchBlogPosts, []),
            returnValue: _i4.Future<List<_i2.BlogPost>>.value(<_i2.BlogPost>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.BlogPost>>.value(
              <_i2.BlogPost>[],
            ),
          )
          as _i4.Future<List<_i2.BlogPost>>);

  @override
  _i4.Future<_i2.BlogPost> fetchBlogPostById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBlogPostById, [id]),
            returnValue: _i4.Future<_i2.BlogPost>.value(
              _FakeBlogPost_0(
                this,
                Invocation.method(#fetchBlogPostById, [id]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.BlogPost>.value(
              _FakeBlogPost_0(
                this,
                Invocation.method(#fetchBlogPostById, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.BlogPost>);

  @override
  _i4.Future<_i2.BlogPost> createBlogPost(_i2.BlogPost? post) =>
      (super.noSuchMethod(
            Invocation.method(#createBlogPost, [post]),
            returnValue: _i4.Future<_i2.BlogPost>.value(
              _FakeBlogPost_0(this, Invocation.method(#createBlogPost, [post])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.BlogPost>.value(
              _FakeBlogPost_0(this, Invocation.method(#createBlogPost, [post])),
            ),
          )
          as _i4.Future<_i2.BlogPost>);
}
